export const defaultCategories = [
  { name: 'salários', type: 'income', avatar: '💶', subCategories: null },
  {
    name: 'atividade independente',
    type: 'income',
    avatar: '💪',
    subCategories: null,
  },
  { name: 'subsídios', type: 'income', avatar: '💷', subCategories: null },
  {
    name: 'prendas (receitas)',
    type: 'income',
    avatar: '🎁',
    subCategories: null,
  },
  {
    name: 'impostos (receitas)',
    type: 'income',
    avatar: '🪙',
    subCategories: null,
  },
  {
    name: 'outras receitas',
    type: 'income',
    avatar: '💰',
    subCategories: null,
  },

  {
    name: 'depósito a prazo',
    type: 'savings',
    avatar: '🏦',
    subCategories: null,
  },
  { name: 'ppr', type: 'savings', avatar: 'ppr', subCategories: null },
  {
    name: 'certificados de aforro/tesouro',
    type: 'savings',
    avatar: '📑',
    subCategories: null,
  },
  {
    name: 'outros investimentos',
    type: 'savings',
    avatar: '💱',
    subCategories: null,
  },

  {
    name: 'transportes',
    type: 'expense',
    avatar: '🚗',
    subCategories: [
      'combustível',
      'inspeções',
      'iuc',
      'manutenção',
      'portagens',
      'prestações',
      'seguros',
    ],
  },
  {
    name: 'animais de estimação',
    type: 'expense',
    avatar: '🐶',
    subCategories: ['alimentação', 'veterinário', 'banhos/tosquia'],
  },
  {
    name: 'atividades extra',
    type: 'expense',
    avatar: '🤸‍♂️',
    subCategories: ['mensalidades', 'equipamento', 'inscrições'],
  },
  {
    name: 'casa',
    type: 'expense',
    avatar: '🏠',
    subCategories: [
      'prestações',
      'condomínio',
      'manutenção/reparações',
      'melhorias/obras',
      'seguros',
    ],
  },
  {
    name: 'despesas de consumo',
    type: 'expense',
    avatar: '🛒',
    subCategories: ['lanches/jantares', 'mercearia/supermercado', 'pão'],
  },
  {
    name: 'cuidados pessoais',
    type: 'expense',
    avatar: '✂️',
    subCategories: ['cabeleireiro/barbeiro', 'manicure/pedicure'],
  },
  {
    name: 'educação',
    type: 'expense',
    avatar: '🚸',
    subCategories: ['alimentação', 'material'],
  },
  { name: 'impostos', type: 'expense', avatar: '🤑', subCategories: null },
  {
    name: 'outras despesas',
    type: 'expense',
    avatar: '🫰',
    subCategories: null,
  },
  {
    name: 'prendas (despesas)',
    type: 'expense',
    avatar: '🎁',
    subCategories: ['amigos', 'família', 'escola'],
  },
  {
    name: 'saúde',
    type: 'expense',
    avatar: '💖',
    subCategories: ['consultas/exames', 'farmácia', 'seguros'],
  },
  {
    name: 'serviços',
    type: 'expense',
    avatar: '📺',
    subCategories: [
      'comunicações',
      'eletricidade',
      'gás',
      'acotes tv/net',
      'subscrições',
      'água',
    ],
  },
  {
    name: 'vestuário/calçado',
    type: 'expense',
    avatar: '👔',
    subCategories: null,
  },
];
